defaultBaseImage: gcr.io/distroless/static
defaultPlatforms:
  - linux/arm64
  - linux/amd64
defaultLdflags:
  - -s
  - -w
  - -X github.com/kro-run/kro/pkg.Version={{.Env.RELEASE_VERSION}}
  - -X github.com/kro-run/kro/pkg.GitCommit={{.Env.GIT_COMMIT}}
  - -X github.com/kro-run/kro/pkg.BuildDate={{.Env.BUILD_DATE}}
